### PR TITLE
Fix format of Thinkerbell rule source getter. r=Yoric

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by Yoric** [comment]
Thanks for the patch, r=me

Bonus points if you manage to add an integration test :)

**Comment by azasypkin** [comment]
> Bonus points if you manage to add an integration test :)

Hm, sure thing, let me take a look at them :)

**Comment by azasypkin** [comment]
Here we're, added two integration tests, waiting for Travis

**Comment by azasypkin** [comment]
Travis is green - merging.

**Pull request merged**
