### PR TITLE
Change ip camera latest image to be Binary type

### PR DESCRIPTION
**Pull request by dhylands**
This allows ipcam.py to work properly.

r? @Yoric

### CODE REVIEW

**Comment by Yoric** [comment]
Sorry about the confusion.

Do you really need all these `print`?

Other than that, r=me.

**Comment by dhylands** [comment]
Without the prints, ipcam.py fails in mysterious ways when somebody goes and changes the getter name. With the prints, it makes it more obvious why something failed.

**Comment by Yoric** [comment]
Well, I do get that I broke something. On the other hand, I suspect that using `debug!` or `info!` from `log` (which is already used in Foxbox) would be a bit nicer.

**Comment by dhylands** [comment]
Merged

**Comment by dhylands** [comment]
The prints are in python code, not rust code

**Pull request merged**
