### PR TITLE
Provide an openzwave profile path to the adapter

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by julienw** [comment]
This goes with https://github.com/fxbox/openzwave-adapter/pull/9, so this needs fxbox/openzwave-stateful-rust#14 to build, and fxbox/openzwave-rust#26 to make it work properly.

**Comment by julienw** [comment]
maybe this also needs to "cargo update" the adapter, I'll make sure to have a proper Cargo.lock before merging.

**Comment by julienw** [comment]
@ferjm r?

**Comment by ferjm** [comment]
r=me

**Pull request merged**
