### PR TITLE
Put a hint in the README.md file about how to figure out which versio…

### PR DESCRIPTION
**Pull request by dhylands**
…n of rust to use.

r? @fabricedesre

### CODE REVIEW

**Comment by fabricedesre** [comment]
Obsoleted by https://github.com/fxbox/foxbox/pull/81 ?

**Comment by dhylands** [comment]
I don't think so. #81 is true today. What I described will continue to work down the road...

**Comment by fabricedesre** [comment]
Right. Can you rebase?

**Comment by dhylands** [comment]
rebased

**Pull request merged**
