### PR TITLE
Show components in logs

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by julienw** [comment]
@fabrice r?

**Comment by julienw** [comment]
ping @fabricedesre ;)

**Comment by fabricedesre** [comment]
Can you paste a few log lines to show how that looks?

**Comment by julienw** [comment]
before:

```
[2016-06-10 11:23:08.572] (6718) INFO  registration server: Starting registration with http://knilxof.org:4242/register
[2016-06-10 11:23:08.572] (6718) INFO  Got ip address: 10.243.30.254
[2016-06-10 11:23:08.575] (6720) INFO  Loaded certificates from directory: "certs/"
[2016-06-10 11:23:08.834] (6730) INFO  UPnP search for devices matching "ssdp:all" (0)
[2016-06-10 11:23:08.834] (6730) INFO  Starting Hue Hub Service for 001788fffe243568
[2016-06-10 11:23:08.836] (6718) INFO  UPnP search for devices matching "urn:cellvision:service:Null:1" (0)
[2016-06-10 11:23:08.839] (6737) INFO  [thinkerbell@link.mozilla.org] Started Thinkerbell main thread.
[2016-06-10 11:23:08.840] (6737) INFO  [thinkerbell@link.mozilla.org] Added Thinkerbell Rule for 'Motion Sensor detects motion, say "Good morning!".'
[2016-06-10 11:23:08.845] (6718) ERROR [OpenzwaveStateful] Unable to locate ZWave USB dongle. The following VID:PIDs were found:
[2016-06-10 11:23:08.848] (6734) WARN  Philips Hue detected but not paired. Please, push pairing button on Philips Hue Bridge ID 001788fffe243568 to start using it.
[2016-06-10 11:23:08.853] (6718) ERROR [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM0
[2016-06-10 11:23:08.853] (6718) ERROR [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM1
[2016-06-10 11:23:08.853] (6718) ERROR [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM2
[2016-06-10 11:23:08.860] (6734) WARN  Push pairing button on Philips Hue Bridge 001788fffe243568
[2016-06-10 11:23:08.895] (6720) INFO  registration server responded with: {"status" : "registered"}
[2016-06-10 11:23:08.895] (6720) INFO  DNS server: Creating DNS entry for local.008357a2e109e61c8fe93861c7e67b0785d02b53.box.knilxof.org
[2016-06-10 11:23:09.040] (6718) INFO  [OpenzwaveAdapter] Started.
[2016-06-10 11:23:09.051] (6743) INFO  Listening for new connections on [::]:4000.
[2016-06-10 11:23:09.242] (6718) INFO  UPnP search for devices matching "ssdp:all" (0)
[2016-06-10 11:23:09.504] (6720) INFO  DNS API response 200 OK
```

after:

```
[2016-06-10 11:20:16.535] (5734) INFO  [foxbox::registration@181] registration server: Starting registration with http://knilxof.org:4242/register
[2016-06-10 11:20:16.535] (5734) INFO  [foxbox::registration@191] Got ip address: 10.243.30.254
[2016-06-10 11:20:16.540] (5736) INFO  [tls::utils@67] Loaded certificates from directory: "certs/"
[2016-06-10 11:20:16.744] (5746) INFO  [foxbox_core::upnp@235] UPnP search for devices matching "ssdp:all" (0)
[2016-06-10 11:20:16.746] (5734) INFO  [foxbox_core::upnp@235] UPnP search for devices matching "urn:cellvision:service:Null:1" (0)
[2016-06-10 11:20:16.748] (5752) INFO  [foxbox::adapters::thinkerbell@393] [thinkerbell@link.mozilla.org] Started Thinkerbell main thread.
[2016-06-10 11:20:16.749] (5752) INFO  [foxbox::adapters::thinkerbell@330] [thinkerbell@link.mozilla.org] Added Thinkerbell Rule for 'Motion Sensor detects motion, say "Good morning!".'
[2016-06-10 11:20:16.763] (5734) ERROR [openzwave_stateful@60] [OpenzwaveStateful] Unable to locate ZWave USB dongle. The following VID:PIDs were found:
[2016-06-10 11:20:16.781] (5734) ERROR [openzwave_stateful@63] [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM0
[2016-06-10 11:20:16.781] (5734) ERROR [openzwave_stateful@63] [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM1
[2016-06-10 11:20:16.781] (5734) ERROR [openzwave_stateful@63] [OpenzwaveStateful]   0bdb:1926 /dev/ttyACM2
[2016-06-10 11:20:16.905] (5736) INFO  [foxbox::registration@106] registration server responded with: {"status" : "registered"}
[2016-06-10 11:20:16.905] (5736) INFO  [foxbox::registration@126] DNS server: Creating DNS entry for local.008357a2e109e61c8fe93861c7e67b0785d02b53.box.knilxof.org
[2016-06-10 11:20:16.968] (5734) INFO  [openzwave_adapter@287] [OpenzwaveAdapter] Started.
[2016-06-10 11:20:16.979] (5760) INFO  [ws@529] Listening for new connections on [::]:4000.
[2016-06-10 11:20:17.081] (5746) INFO  [foxbox::adapters::philips_hue::hub@47] Starting Hue Hub Service for 001788fffe243568
[2016-06-10 11:20:17.096] (5770) WARN  [foxbox::adapters::philips_hue::hub@64] Philips Hue detected but not paired. Please, push pairing button on Philips Hue Bridge ID 001788fffe243568 to start using it.
[2016-06-10 11:20:17.108] (5770) WARN  [foxbox::adapters::philips_hue::hub@85] Push pairing button on Philips Hue Bridge 001788fffe243568
[2016-06-10 11:20:17.173] (5734) INFO  [foxbox_core::upnp@235] UPnP search for devices matching "ssdp:all" (0)
[2016-06-10 11:20:17.529] (5736) INFO  [tls::dns_client@59] DNS API response 200 OK
```

The fact we miss the module (which is actually displayed when we use env_logger's default) makes it necessary to add things like `[OpenzwaveAdapter]` to know where the log comes from. Especially important at the debug level, but also useful in info level.

I could be convinced to remove the line number, but I find it useful too.

**Comment by fabricedesre** [comment]
works for me, please merge!

**Comment by dhylands** [comment]
Personally, I find that adding the location totally messes up the indentation of the logging messages themselves and makes it much harder to read.

Having said that, there are distinct advantages to having the location show up.

But I'd prefer to see it runtime controllable, perhaps using a configuration option or command line switch.

**Comment by julienw** [comment]
I like to see the location as part of the logging message, so that's why I don't see the bad indentation. But maybe we could put the location at the end of the message instead of at the start. What do you think @dhylands ?

**Comment by dhylands** [comment]
I think it would be better at the end, although its one of those things I'd have to see.

**Pull request merged**
