### PR TITLE
Yoric

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

**Comment by fabricedesre** [comment]
Can you squash and make sure the commit message is the right one?

**Comment by Yoric** [comment]
Too.... many... things... in... brain.

**Comment by fabricedesre** [comment]
hm, looks like this was rolled up in https://github.com/fxbox/foxbox/commit/68db3433b557d87e7015adc127072e72552c06a4 ?

**Comment by fabricedesre** [comment]
closing for now...

**Comment by Yoric** [comment]
Possibly a collateral damage of too much multitasking. Sorry about that. Need...to...sleep.

**Pull request closed without merging**
