### PR TITLE
Thinkerbell: Deactivate test_rules::test_run for being intermittent

### LINKED ISSUE #439: Intermittent: One of the thinkerbell test hangs for more than 10 minutes
It occurs more recurrently these days (I would say 4/10 runs on Travis).  For example, see: https://travis-ci.org/fxbox/foxbox/jobs/126068011#L1466

cc @Yoric

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Fixes #439

### CODE REVIEW

**Comment by Yoric** [comment]
@JohanLorenzo So this test causes the intermittent error?

**Comment by JohanLorenzo** [comment]
@Yoric I'm not 100% sure. Based on https://travis-ci.org/fxbox/foxbox/jobs/129085656 and https://travis-ci.org/fxbox/foxbox/jobs/126068011 + a couple more I saw : This test is never mentioned to be done. 

I'll re-run the travis job 4 more times to see if my guess is correct.

**Comment by JohanLorenzo** [comment]
`test_rules::test_run` is likely the test hanging. After I deactivated it, it hasn't failed 5 out of 5 times.

r? @Yoric

**Comment by Yoric** [comment]
Any chance you could try and bissect what part of the test causes hanging? I can understand if you don't have time, mind you.

**Comment by JohanLorenzo** [comment]
@Yoric I'm not sure how much time the bisection will take. Since this problem has taken around 15 days to be identified, I'd prefer to first deactivate the test, and then bisect it. What do you think?

**Comment by Yoric** [comment]
Sure.

**Comment by Yoric** [comment]
In that case, r=me.

**Pull request merged**
