### PR TITLE
Intermittent test failures in service_router. r=cr

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by ferjm** [comment]
@cr r?

I didn't manage to reproduce the intermittent, so I can't confirm that this fixes it. My theory is that because tests are running in separate threads and we were clearing and recreating the users db on the `before_each` block of each test, it was possible that one of the requests done inside the tests was done in between the clear and creation of the db and so it was being rejected with the 401 cause no admin user existed at that point. With this patch we only clear and create the db once.

**Comment by ferjm** [comment]
#114

**Comment by cr** [comment]
It doesn't fix the intermittent failures for me.

**Comment by ferjm** [comment]
@cr could you try with the latest commit, please? If that doesn't help, could you paste the output of running the tests with `RUST_BACKTRACE=1`, please? Thanks!

**Comment by cr** [comment]
Still failing:

```
$ RUST_BACKTRACE=1 cargo test
     Running target/debug/foxbox-85240ed05703f83c

running 40 tests
test controller::controller::add_service::should_create_http_root ... ok
test controller::controller::add_service::should_increase_number_of_services ... ok
test controller::controller::add_service::should_create_ws_root ... ok
test controller::controller::add_service::should_make_service_available ... ok
test controller::controller::add_service::should_return_a_json ... ok
test controller::controller::should_delete_a_service ... ok
test config_store::config_store::should_return_None_on_non-existent_namespaces ... ok
test config_store::config_store::should_remember_things_over_restarts ... ok
test config_store::config_store::should_return_None_on_non-existent_properties ... ok
test config_store::config_store::should_remember_properties ... ok
test managed_process::test_managed_process_shutdown ... ok
test registration::registrar::ipv4::should_default_to_eth0 ... ok
test registration::registrar::ipv4::should_retrieve_address_from_docker0 ... ok
test registration::registrar::ipv4::should_retrieve_address_from_eth0 ... ok
test registration::registrar::ipv4::should_retrieve_address_from_wlan0 ... ok
test registration::registrar::ipv6::should_return_IPv4_and_eth0_by_default ... ok
test registration::registrar::ipv6::should_return_IPv4_if_both_are_specified ... ok
test registration::registrar::ipv6::should_return_IPv6 ... ok
test service::service::should_be_serializable ... ok
test registration::registrar::should_return_an_IP_address_when_a_machine_has_network_interfaces ... ok
test service_router::service_router::cors::should_get_the_appropriate_CORS_headers ... ok
test stable_uuid::stable_uuid::should_generate_stable_UUIDs ... ok
test utils::json::arrays::should_support_mixed_types ... ok
test utils::json::arrays::should_support_numbers ... ok
test utils::json::arrays::should_support_objects ... ok
test service_router::service_router::services::should_make_service_available ... ok
test utils::json::arrays::should_support_sub-arrays ... ok
test utils::json::arrays::should_support_sub-sub-arrays ... ok
test utils::json::objects::should_support_arrays ... ok
test service_router::service_router::services::should_create_list.json ... ok
test utils::json::objects::should_support_mixed_types ... ok
test utils::json::objects::should_support_numbers ... ok
test utils::json::objects::should_support_string_attributes ... ok
test utils::json::objects::should_support_sub-objects ... ok
test utils::json::objects::should_support_sub-sub-objects ... ok
test service_router::service_router::services::should_return_an_error_if_no_service_was_found ... FAILED
test main::args::should_have_default_values ... ok
test main::args::should_support_short_form ... ok
test main::args::should_support_long_form ... ok
test managed_process::test_managed_process_restart ... ok

failures:

---- service_router::service_router::services::should_return_an_error_if_no_service_was_found stdout ----
        thread 'service_router::service_router::services::should_return_an_error_if_no_service_was_found' panicked at 'called `Result::unwrap()` on an `Err` value: IronError { error: StringError("Unauthorized"), response: HTTP/1.1 401 Unauthorized Unauthorized
Content-Length: 47

 }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x103ab79c8 - sys::backtrace::tracing::imp::write::hbf901342cf42dd32Plu
   2:        0x103abb535 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43106
   3:        0x103abb097 - panicking::default_handler::hc39cc975176a9eeceNy
   4:        0x103aaa836 - sys_common::unwind::begin_unwind_inner::h669bcd18f61ce724Bkt
   5:        0x103aaacee - sys_common::unwind::begin_unwind_fmt::h0b459adbd1db05b5Hjt
   6:        0x103ab6f87 - rust_begin_unwind
   7:        0x103add6a0 - panicking::panic_fmt::h38cc775b27fedfe3yZL
   8:        0x103736150 - result::unwrap_failed::h8830953082448509810
   9:        0x103735ed9 - result::Result<T, E>::unwrap::h12880513666818903765
  10:        0x103763925 - service_router::service_router::services::should_return_an_error_if_no_service_was_found::h7f6e882e547bf179WFh
  11:        0x103a8d02b - boxed::F.FnBox<A>::call_box::h10815167147045881405
  12:        0x103a8f49d - sys_common::unwind::try::try_fn::h15128236275633275219
  13:        0x103ab6f1b - __rust_try
  14:        0x103ab4903 - sys_common::unwind::inner_try::h0e1de7affe5c603fDht
  15:        0x103a8f884 - boxed::F.FnBox<A>::call_box::h16664783708598344985
  16:        0x103aba7bc - sys::thread::Thread::new::thread_start::hc3d94e540e78e483F1x
  17:     0x7fff9b7aec12 - _pthread_body
  18:     0x7fff9b7aeb8f - _pthread_start


failures:
    service_router::service_router::services::should_return_an_error_if_no_service_was_found

test result: FAILED. 39 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by ferjm** [comment]
@JohanLorenzo any idea about what's wrong here? I can't reproduce it locally and it seems that in travis this is working just fine.

**Comment by ferjm** [comment]
service_router is gone now

**Pull request closed without merging**
