### PR TITLE
Add information about the docker image

### PR DESCRIPTION
**Pull request by fabricedesre**

### CODE REVIEW

**Comment by cr** [comment]
Docker on OS X isn't straight forward. The official doc at https://docs.docker.com/engine/installation/mac/ isn't helpful at all if your prefer homebrew, so I didn't follow that one. For setting up docker and virtualbox the homebrew way, I essentially followed http://sticksnglue.com/wordpress/a-future-without-boot2docker-featuring-docker-machine/ instead.

After  running that final `eval` comand, I can `docker pull` your image as described, but `docker run` has issues:

``` bash
$ docker run -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo cargopi build
Unable to find image 'cargopi:latest' locally
Pulling repository docker.io/library/cargopi
docker: Error: image library/cargopi not found.
See 'docker run --help'.
```

To be honest, I have no understanding of how docker and interacting with containers works, so I can't even say what those paths are referring to and whether or not I need to change them.

Perhaps this is helpful:

``` bash
$ docker --version
Docker version 1.10.0, build 590d510

$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
dev       *        virtualbox   Running   tcp://192.168.99.101:2376           v1.10.1   

$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
fabricedesre/rustpi2   latest              e9b71fd59895        9 hours ago         800.1 MB

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: AAD4:TBP5:ZQPW:KSTH:ZJCR:FYIX:3VKV:CAEB:TS3A:Z2D2:H55O:OOEJ
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-02-13T10:15:26.266577781Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by fabricedesre** [comment]
There was a mistake in the `docker run` command... Can you try again?

**Comment by fabricedesre** [comment]
@cr Also, did you try the installer linked from https://docs.docker.com/mac/step_one/ ?

**Comment by cr** [comment]
I haven't used Docker's official installer or toolbox. I prefer homebrew so I can easily update and uninstall. I'd say it's basically working now. Your new docker command works... in a way:

``` bash
$ docker run -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build
 Downloading url v0.5.4
 Downloading aho-corasick v0.4.1
 Downloading docopt_macros v0.6.80
 Downloading language-tags v0.2.1
   Compiling byteorder v0.4.2
   Compiling lazy_static v0.1.15
[...]
   Compiling websocket v0.15.0
   Compiling foxbox v0.1.0 (file:///home/rustpi2/source)
   Compiling quasi_codegen v0.4.0
   Compiling quasi_macros v0.4.0
   Compiling serde_macros v0.6.11
src/controler.rs:10:5: 10:15 error: import `mio` conflicts with imported crate in this module (maybe you meant `use mio::*`?) [E0254]
src/controler.rs:10 use events::*;
                        ^~~~~~~~~~
error: aborting due to previous error
Could not compile `foxbox`.

To learn more, run the command again with --verbose.
```

This was re-building my local development tree (which builds fine using my native rustc). Interestingly, when I checkout a fresh tree, it's worse:

``` bash
$ docker run -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build
could not find `Cargo.toml` in `/home/rustpi2/source` or any parent directory
```

Am I missing a cargo install step there?

**Comment by fabricedesre** [comment]
the `use events::*;` issue has been fixed in https://github.com/fxbox/foxbox/commit/ab61bc82c424239bc147997c56371e1015da507a

For the `could not find `Cargo.toml`` one, are you sure you were in the directory where you checked out the code?

**Comment by cr** [comment]
This is the directory I called the second `docker run` command in:

``` bash
$ pwd
/tmp/foxbox
$ git branch -v
* master c5d7803 Merge pull request #46 from fabricedesre/master
$ ls
Cargo.lock  LICENSE     build.rs    src/        test/
Cargo.toml  README.md   docs/       static/     tools/
```

**Comment by cr** [comment]
I moved the fresh git tree from /tmp to my home directory, and now the behavior has changed:

``` bash
$ pwd
/Users/cruetten/src/foxbpx2
$ docker run -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build --verbose
    Updating git repository `https://github.com/fxbox/users.git`
Unable to update https://github.com/fxbox/users.git?rev=78d3e2f#78d3e2ff

Caused by:
  failed to fetch into /home/rustpi2/.cargo/git/db/users-e24776817d8707bd

Caused by:
  [2/-1] Failed to mmap. Could not write data: Invalid argument
```

Did something inside the docker container get messed up? Is there an easy way to reset?

**Comment by dscravag** [comment]
I am having the exact same error as cr

``` bash
14-02-2016 00:13:41 david@david-computer ~/Documents/dev/mozilla/foxbox $ 
docker run -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [2/-1] Failed to mmap. Could not write data: Invalid argument
```

**Comment by dscravag** [comment]
FYI I used the standard install of Docker

**Comment by arcturus** [comment]
I get the error related to SSL compilation in macosx:

failed to run custom build command for `openssl v0.7.5`
Process didn't exit successfully: `/home/rustpi2/source/target/debug/build/openssl-bf2ed9545558cfe0/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("armv7-unknown-linux-gnueabihf")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("x86_64-unknown-linux-gnu")
CC_armv7-unknown-linux-gnueabihf = None
CC_armv7_unknown_linux_gnueabihf = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_armv7-unknown-linux-gnueabihf = None
CFLAGS_armv7_unknown_linux_gnueabihf = None
TARGET_CFLAGS = Some("-I /opt/rustpi2/x-tools/arm-unknown-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-I" "/opt/rustpi2/x-tools/arm-unknown-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf" "-g" "-fPIC" "-o" "/home/rustpi2/source/target/armv7-unknown-linux-gnueabihf/debug/build/openssl-bf2ed9545558cfe0/out/src/c_helpers.o" "-c" "src/c_helpers.c"
ExitStatus(ExitStatus(256))

I tried to add the volume of my hd: -v /usr/local/opt/openssl where my openssl headers live, but when doing in the machine a simple ls /usr/local/opt/openssl it doesnt include the subdirectories :S ... i'm definitely a newbie in docker.

**Comment by arcturus** [comment]
And no luck specifying where the headers for ssl are, as I realised those are in the image:

docker run -e RUST_BACKTRACE=1 -e OPENSSL_INCLUDE_DIR=/opt/rustpi2/x-tools/arm-unknown-linux-gnueabihf/sysroot/usr/include -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build

**Comment by arcturus** [comment]
I think I'm improving as the sources directory needs to end up in DEP_OPENSSL_INCLUDE, so my command now looks like:

docker run -e DEP_OPENSSL_INCLUDE=/opt/rustpi2/x-tools/arm-unknown-linux-gnueabihf/sysroot/usr/include -v `pwd`:/home/rustpi2/source -v $HOME/.cargo:/home/rustpi2/.cargo fabricedesre/rustpi2 cargopi build

Getting the following error :
/opt/rustpi2/x-tools/arm-unknown-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory

Which is true, since i have stubs-hard.h basically cause we are compiling against arm-unknown-linux-gnueabiHF

**Comment by arcturus** [comment]
Working for me with last docker image and not mounting the .cargo volume:

```
docker run -v `pwd`:/home/rustpi2/dev/source fabricedesre/rustpi2 cargopi build
```

Tested the executable in the pi and working pretty nice.

**Pull request closed without merging**
