### PR TITLE
Thinkerbell Adapter now expects rules as an object instead of a serialized string.

### PR DESCRIPTION
**Pull request by Yoric**
This should make things a bit more readable and a bit more robust.

In particular, this should fix 1) of https://github.com/fxbox/foxbox/pull/520#issuecomment-224869077 .

### CODE REVIEW

**Comment by Yoric** [comment]
Also, f? @azasypkin for the API changes. See changes in the tests for details.

**Comment by mcav** [comment]
lgtm

**Comment by azasypkin** [comment]
f+, looks good to me, just one question: is it expected that source getter still returns string instead of plain object? 

`https://local.609aebe9f46a699f80d6e0284c3334ddf879e125.box.knilxof.org:3000/api/v1/channels/get' -X PUT -H ..... --data-binary '[{"id":"thinkerbell/Everyday in the morning, camera takes a picture./source"}]'
`

Response:
`{"thinkerbell/Everyday in the morning, camera takes a picture./source":"{\"name\":\"Everyday in the morning, camera takes a picture.\",\"rules\":[{\"conditions\":[{\"feature\":\"clock/time-of-day-seconds\",\"source\":[{\"id\":\"getter:timeofday.clock@link.mozilla.org\"}],\"when\":{\"Geq\":{\"Duration\":28800}}}],\"execute\":[{\"destination\":[{\"id\":\"channel:snapshot.18db9b78-f188-11e5-9ce9-3ca9f47e346c@link.mozilla.org\"}],\"feature\":\"camera/store-snapshot\",\"value\":null}]}]}"}
`

**Comment by Yoric** [comment]
Good catch. I'll make both match.

**Comment by Yoric** [comment]
Ok, fixed.

@mcav, if you have a chance to take a look at the revised version, that would be great.

**Comment by mcav** [comment]
Okay, still looks good to me

**Pull request merged**
