### PR TITLE
Travis: Deactivate only the test using github.io

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Follow up #463

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Based on [this Travis job](https://travis-ci.org/fxbox/foxbox/jobs/127838483), I believe we can just take out github.io test, which should bring things back to what they used to be (before Friday). What do think @isabelrios @npark-mozilla ? r?

**Comment by nojunpark** [comment]
yup agreed

**Comment by isabelrios** [comment]
Agreed

**Comment by JohanLorenzo** [comment]
Tests in components were failing because of https://github.com/fxbox/foxbox/issues/468 . Like said in [this comment](https://github.com/fxbox/foxbox/pull/464#issuecomment-216921688), we can see the effect of pinpointing the tests to deactivate in the travis job. 

Landing.

**Pull request merged**
