### PR TITLE
Integrate "segfault" fix in multicast_dns crate - flaw in AvahiAdapter Drop trait impementation.

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by azasypkin** [comment]
Let's see first what Travis thinks about this fix :)

**Comment by azasypkin** [comment]
He @fabricedesre, could you please try this PR and see if you notice any segfaults/unexpected crashes on rpi/desktop? Haven't noticed anything like this so far, hopefully the issue is fixed now.

**Comment by fabricedesre** [comment]
Works fine for me now!

**Comment by azasypkin** [comment]
Cool, thanks - let's see how it goes then :)

**Pull request merged**
