### PR TITLE
OpenzwaveAdapter::init now returns an Arc

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by julienw** [comment]
Needed for https://github.com/fxbox/openzwave-stateful-rust/pull/20

**Comment by julienw** [comment]
I filed a bug at rsnotify: https://github.com/passcod/rsnotify/issues/82

**Comment by julienw** [comment]
r? @JohanLorenzo @fabricedesre 

likely my final patch in foxbox :D

**Comment by JohanLorenzo** [comment]
LGTM!

**Comment by fabricedesre** [comment]
r=me

**Pull request merged**
