### PR TITLE
Fix UserDb API usage following changes for issue fxbox/users#53

### PR DESCRIPTION
**Pull request by hfiguiere**
We need fxbox/users#66 to be merged. This reference my own branch.

### CODE REVIEW

**Comment by hfiguiere** [comment]
@fabricedesre this might be useful for issue #142. Albeit here I hardcode the file name instead of getting it from the configuration.

**Comment by hfiguiere** [comment]
This PR needs some work. Test failures.

**Comment by ferjm** [comment]
FWIW I'd like to take a different approach https://github.com/fxbox/users/pull/66#issuecomment-195036992

**Comment by hfiguiere** [comment]
@fabricedesre @ferjm r? (need the changes for fxbox/users#53 and a readjustment of the Cargo.toml once they land)

**Comment by hfiguiere** [comment]
(rebased again)

Also I support the new stuff from PR #184

**Comment by hfiguiere** [comment]
I have addressed 2 of the 3 comments. I still believe we should not have a default path for the database. Because:
1. if it is relative to cwd() it is error prone. Change the working directory and boom.
2. if it is absolute it is also error prone as there is a strong chance that another library user could try to access it.

**Comment by hfiguiere** [comment]
Now that the other PR has been merged, this is read for @fabricedesre @ferjm r?

**Comment by ferjm** [comment]
LGTM. Thanks!

**Pull request merged**
