### PR TITLE
Issue #69 - Add -i/--iface to specify an interface

### PR DESCRIPTION
**Pull request by hfiguiere**
-Also return an error if no IP address is found
-Stop iterating if one IP address was found.
-Add em to the iface whitelist since:
[    2.340010] e1000e 0000:00:19.0 em1: renamed from eth0

### CODE REVIEW

**Comment by hfiguiere** [comment]
@arcturus @fabricedesre r?

The command-line override the white-list. Also fixed some bugs in get_ip_addr() (see commit message)

Haven't tested on rpi as I don't have hardware.

**Comment by arcturus** [comment]
LGTM, tested and working fine even with interfaces that are not in the white list. r+

**Comment by hfiguiere** [comment]
I wrote some more testing. Updated the PR because it is important to test.

**Comment by hfiguiere** [comment]
@fabricedesre r?

**Pull request merged**
