### PR TITLE
sending service bips to the event loop

### PR DESCRIPTION
**Pull request by jedireza**
Related to: #65

### CODE REVIEW

**Comment by jedireza** [comment]
r? @fabricedesre 

So this will send the service bips to the event loop, which automatically get sent to the websocket clients. Sorry about the whitespace noise, I wanted to clean up the readability while I was at it.

**Comment by fabricedesre** [comment]
We need something that is not specific to the dummyservice (it should be remove at some point).

Instead, consider doing something that let any service send back either a string or a vec<u8> since this is what our ws library supports (http://housleyjk.github.io/ws-rs/ws/struct.Sender.html#method.send) I haven't checked if that maps to ArrayBuffers or ArrayBufferViews on the client side but that doesn't matter much. 

That all lead to really wonder if having a single websocket is a good option. For an app connected to a box an interacting with several services it's impossible to know who's sending what in general, and for binary payloads especially. Eg if 2 cameras sends pictures as ArrayBuffer, how do we distinguish them?

**Comment by jedireza** [comment]
> We need something that is not specific to the dummyservice (it should be remove at some point).
> 
> Instead, consider doing something that let any service send back either a string or a vec since this is what our ws library supports (http://housleyjk.github.io/ws-rs/ws/struct.Sender.html#method.send) I haven't checked if that maps to ArrayBuffers or ArrayBufferViews on the client side but that doesn't matter much.

I added a new event type and sent it to the event loop and from there the controller dispatches messages to the websockets. We do need to get more specific about these events; what kinds we have, the data they contain and how they're consumed (ex: serialized to json for websocket client consumption).

> That all lead to really wonder if having a single websocket is a good option. For an app connected to a box an interacting with several services it's impossible to know who's sending what in general, and for binary payloads especially. Eg if 2 cameras sends pictures as ArrayBuffer, how do we distinguish them?

It should be trivial for the central websocket connection to handle most (90%+) of our event communication. Raw camera feeds are indeed a special case that should be handled outside of the central websocket connection.

**Comment by fabricedesre** [comment]
Websocket payloads in ws-rs are either Strings or Vects of u8. We should also support any struct implementing Serialize and send it as a json representation. The current PR only does String.

I don't understand your argument about the central websocket connection. With a single websocket, we'll need to have some ID be part of every message, and that's really hard for any non-structured message. How do you plan to distinguish between 2 opaque vectors of bytes?

**Comment by jedireza** [comment]
Our ideas about the implementation are drifting. Let's setup a time to sync-up. Closing this PR for now, there's not much to it.

**Pull request closed without merging**
