### PR TITLE
Update Cargo and fix openzwave adapter

### PR DESCRIPTION
**Pull request by fabricedesre**

### CODE REVIEW

**Comment by fabricedesre** [comment]
@julienw and @dhylands : this fails to build on mac because of a platform specific issue in notify::FsEventWatcher
Can you take a look? thanks!

**Comment by julienw** [comment]
yeah I know; I think we should backout the change from openzwave-stateful-rust in the meantime.

**Comment by fabricedesre** [comment]
That, or pin the rev of openzwave-stateful-rust in components/openzwave-adapter ?

**Comment by julienw** [comment]
yeah why not; let me do this

**Comment by julienw** [comment]
https://github.com/fxbox/foxbox/pull/533, waiting for a green travis

**Pull request closed without merging**
