### PR TITLE
rust up

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by julienw** [comment]
@fabrice r? :)

**Comment by fabrice** [comment]
Hey. You aren't talking to the right fabrice. **;)**

**Comment by julienw** [comment]
ah sorry, and I know it's not the first time !

**Comment by julienw** [comment]
@fabricedesre r? ;)

**Comment by fabricedesre** [comment]
Why 06-24 and not 06-28 ?

**Comment by julienw** [comment]
There is no build since 06-24 (at least when I tried earlier today)

**Comment by fabricedesre** [comment]
ok then, r=me

**Pull request merged**
