### PR TITLE
WebPushNotify now uses ChannelKind::WebPushNotify

### PR DESCRIPTION
**Pull request by Yoric**
r? @aosmond 

This should fix the issue encountered by @ferjm when attempting to test WebPush with Thinkerbell.

Cc @gmarty and @arcturus in case they rely upon the old channelkind.

### CODE REVIEW

**Comment by ferjm** [comment]
I'm testing this patch, but you may want @aosmond to take a look at the code.

**Comment by Yoric** [comment]
Well, r? @aosmond .

**Comment by aosmond** [comment]
@Yoric r-. This isn't complete because we would need to change the send_values like I did in https://github.com/fxbox/foxbox/pull/351 no? I rebased it so it can merge once travis passes....

**Comment by Yoric** [comment]
@aosmond I don't really see the difference between our PRs. So pick one and land it :)

**Comment by ferjm** [comment]
FWIW the patch works :)

**Comment by Yoric** [comment]
Landed as discussed with @aosmond .

**Pull request merged**
